services:
  mongodb:
    image: mongo:8.2-ubi8
    container_name: mongodb
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongo_data:/data/db
    restart: always

  farkle:
    build: 
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/farkle:${GIT_TAG:-dev}
    ports:
      - ${SSH_PORT:-2222}:${ASCII_ARCADE_SSH_PORT:-2222}
      - ${WEB_PORT:-8080}:${ASCII_ARCADE_WEB_PORT:-8080}
    env_file:
      - .env
    restart: always
    volumes:
      - farkle_ssh:/app/.ssh
volumes:
  farkle_ssh:
  mongo_data:
