services:
  farkle:
    build: 
      context: .
      args:
        - GIT_TAG=latest
    image: ascii-arcade/farkle:${GIT_TAG}
    ports:
      - "2022:2022"
      - "8080:8080"
    restart: always
    environment:
      - ASCII_ARCADE_SSH_PORT=2022
      - ASCII_ARCADE_WEB_PORT=8080
      - ASCII_ARCADE_HOST=0.0.0.0
    volumes:
      - farkle_ssh:/app/.ssh
volumes:
  farkle_ssh:
